from __future__ import annotations

from datetime import datetime
from enum import Enum

from pydantic import BaseModel
from pydantic import Field


class DetectionClass(str, Enum):
    """
    Supported detection classes.

    Initially we only use PERSON.
    Additional classes can be enabled later.
    """

    PERSON = "person"


class BoundingBox(BaseModel):
    """
    Pixel coordinates in image space.

    x1,y1 = top-left
    x2,y2 = bottom-right
    """

    x1: float
    y1: float
    x2: float
    y2: float

    @property
    def width(self) -> float:
        return self.x2 - self.x1

    @property
    def height(self) -> float:
        return self.y2 - self.y1

    @property
    def area(self) -> float:
        return self.width * self.height


class Detection(BaseModel):
    """
    Single object detection.

    Generated by YOLO.
    Consumed by:
    - ByteTrack
    - ReID
    - Pose
    - Rules
    """

    camera_id: str

    frame_id: int

    timestamp: datetime

    class_id: int

    class_name: DetectionClass

    confidence: float = Field(
        ge=0.0,
        le=1.0,
    )

    bbox: BoundingBox


class DetectionResult(BaseModel):
    """
    All detections for a frame.
    """

    camera_id: str

    frame_id: int

    timestamp: datetime

    detections: list[Detection]