#!/usr/bin/env bash
# Pin every camera currently on the CERAVIS hotspot to its present IP, so a
# reboot (or the nightly reboot) can never hand a camera a different address.
#
# Why this matters: the edge stores each camera's RTSP + ONVIF endpoints BY IP
# (schemas/cameras.py -> rtsp_url, onvif_xaddr), and MediaMTX dials that exact
# rtsp_url. If DHCP moved a camera to a new IP, its stream would silently go
# dark until a re-scan. This writes DHCP RESERVATIONS (MAC -> IP) into the
# hotspot's own dnsmasq, so each camera keeps its address forever. Cameras stay
# on plain DHCP — nothing to configure on the camera itself.
#
# Run this ONCE, AFTER the cameras have joined the hotspot and show up on the
# Hotspot page:   bash setup/pin_camera_ips.sh
# To unpin everything, delete the drop-in file it writes and restart the hotspot.
set -euo pipefail

CON=ceravis-hotspot
DROPIN=/etc/NetworkManager/dnsmasq-shared.d/ceravis-cameras.conf

# NetworkManager's shared-mode dnsmasq records its leases here, one file per
# shared interface. These are the SAME files the /hotspot API reads to list
# connected devices, so a camera visible on the Hotspot page is a lease here.
LEASES="$(cat /var/lib/NetworkManager/dnsmasq-*.leases 2>/dev/null || true)"
if [ -z "${LEASES//[[:space:]]/}" ]; then
    echo "No DHCP leases found — no devices are on the hotspot yet." >&2
    echo "  Start the hotspot, join the cameras, confirm them on the Hotspot" >&2
    echo "  page, then re-run:  bash setup/pin_camera_ips.sh" >&2
    exit 1
fi

# Lease line:  <expiry> <mac> <ip> <hostname> <client-id>
TMP="$(mktemp)"
{
    echo "# CERAVIS camera IP reservations — generated by setup/pin_camera_ips.sh"
    echo "# Re-run that script after adding a camera; delete this file to unpin."
    n=0
    while read -r _expiry mac ip host _rest; do
        [ -n "${mac:-}" ] && [ -n "${ip:-}" ] || continue
        echo "dhcp-host=$mac,$ip   # ${host:-camera}"
        n=$((n+1))
    done <<< "$LEASES"
    echo "# $n reservation(s)"
} > "$TMP"

sudo mkdir -p "$(dirname "$DROPIN")"
sudo cp "$TMP" "$DROPIN"
rm -f "$TMP"

echo "Wrote $DROPIN:"
sudo sed 's/^/  /' "$DROPIN"

# Reload the hotspot so dnsmasq re-reads the drop-in. Cameras briefly drop and
# rejoin; from here each keeps the address pinned above across every reboot.
if nmcli -t -f NAME connection show --active 2>/dev/null | grep -qx "$CON"; then
    echo "Reloading hotspot to apply the reservations..."
    nmcli connection down "$CON" >/dev/null 2>&1 || true
    nmcli connection up   "$CON" >/dev/null 2>&1 || sudo nmcli connection up "$CON"
    echo "Done — camera IPs are now fixed across reboots."
else
    echo "NOTE: hotspot is not active; reservations apply next time it starts."
fi
